<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp\ConfigWrite;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * configuration layer
 *
 * Generated from protobuf message <code>mpp.ConfigWrite.Layer</code>
 */
class Layer extends \Google\Protobuf\Internal\Message
{
    /**
     * IDs of the changed symbols (in ascending order)
     *
     * Generated from protobuf field <code>repeated uint32 set_symbol_ids = 1;</code>
     */
    private $set_symbol_ids;
    /**
     * values of the changed symbols as a continuous buffer
     *
     * Generated from protobuf field <code>bytes set_symbol_values = 2;</code>
     */
    protected $set_symbol_values = '';
    /**
     * IDs of the cleared symbols (in ascending order)
     *
     * Generated from protobuf field <code>repeated uint32 clear_symbol_ids = 3;</code>
     */
    private $clear_symbol_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $set_symbol_ids
     *           IDs of the changed symbols (in ascending order)
     *     @type string $set_symbol_values
     *           values of the changed symbols as a continuous buffer
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $clear_symbol_ids
     *           IDs of the cleared symbols (in ascending order)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * IDs of the changed symbols (in ascending order)
     *
     * Generated from protobuf field <code>repeated uint32 set_symbol_ids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSetSymbolIds()
    {
        return $this->set_symbol_ids;
    }

    /**
     * IDs of the changed symbols (in ascending order)
     *
     * Generated from protobuf field <code>repeated uint32 set_symbol_ids = 1;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSetSymbolIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->set_symbol_ids = $arr;

        return $this;
    }

    /**
     * values of the changed symbols as a continuous buffer
     *
     * Generated from protobuf field <code>bytes set_symbol_values = 2;</code>
     * @return string
     */
    public function getSetSymbolValues()
    {
        return $this->set_symbol_values;
    }

    /**
     * values of the changed symbols as a continuous buffer
     *
     * Generated from protobuf field <code>bytes set_symbol_values = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSetSymbolValues($var)
    {
        GPBUtil::checkString($var, False);
        $this->set_symbol_values = $var;

        return $this;
    }

    /**
     * IDs of the cleared symbols (in ascending order)
     *
     * Generated from protobuf field <code>repeated uint32 clear_symbol_ids = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClearSymbolIds()
    {
        return $this->clear_symbol_ids;
    }

    /**
     * IDs of the cleared symbols (in ascending order)
     *
     * Generated from protobuf field <code>repeated uint32 clear_symbol_ids = 3;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClearSymbolIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->clear_symbol_ids = $arr;

        return $this;
    }

}

