<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp\Msg;

use UnexpectedValueException;

/**
 * message types
 *
 * Protobuf type <code>mpp.Msg.MsgType</code>
 */
class MsgType
{
    /**
     * no payload
     *
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * payload = SessionBegin
     *
     * Generated from protobuf enum <code>SESSION_BEGIN = 1;</code>
     */
    const SESSION_BEGIN = 1;
    /**
     * payload = SessionEnd
     *
     * Generated from protobuf enum <code>SESSION_END = 2;</code>
     */
    const SESSION_END = 2;
    /**
     * payload = Samples
     *
     * Generated from protobuf enum <code>SAMPLES = 3;</code>
     */
    const SAMPLES = 3;
    /**
     * payload = SymbolInval
     *
     * Generated from protobuf enum <code>SYMBOL_INVAL = 4;</code>
     */
    const SYMBOL_INVAL = 4;
    /**
     * payload = UpdateStart
     *
     * Generated from protobuf enum <code>UPDATE_START = 5;</code>
     */
    const UPDATE_START = 5;
    /**
     * payload = UpdateResult
     *
     * Generated from protobuf enum <code>UPDATE_START_RESULT = 6;</code>
     */
    const UPDATE_START_RESULT = 6;
    /**
     * payload = UpdateCancel
     *
     * Generated from protobuf enum <code>UPDATE_CANCEL = 7;</code>
     */
    const UPDATE_CANCEL = 7;
    /**
     * payload = UpdateResult
     *
     * Generated from protobuf enum <code>UPDATE_CANCEL_RESULT = 8;</code>
     */
    const UPDATE_CANCEL_RESULT = 8;
    /**
     * payload = UpdateResult
     *
     * Generated from protobuf enum <code>UPDATE_SESSION_RESULT = 9;</code>
     */
    const UPDATE_SESSION_RESULT = 9;
    /**
     * Generated from protobuf enum <code>RT_SAMPLING_START = 10;</code>
     */
    const RT_SAMPLING_START = 10;
    /**
     * Generated from protobuf enum <code>RT_SAMPLING_STOP = 11;</code>
     */
    const RT_SAMPLING_STOP = 11;
    /**
     * Generated from protobuf enum <code>MARK_ORIENTATION = 12;</code>
     */
    const MARK_ORIENTATION = 12;

    private static $valueToName = [
        self::NONE => 'NONE',
        self::SESSION_BEGIN => 'SESSION_BEGIN',
        self::SESSION_END => 'SESSION_END',
        self::SAMPLES => 'SAMPLES',
        self::SYMBOL_INVAL => 'SYMBOL_INVAL',
        self::UPDATE_START => 'UPDATE_START',
        self::UPDATE_START_RESULT => 'UPDATE_START_RESULT',
        self::UPDATE_CANCEL => 'UPDATE_CANCEL',
        self::UPDATE_CANCEL_RESULT => 'UPDATE_CANCEL_RESULT',
        self::UPDATE_SESSION_RESULT => 'UPDATE_SESSION_RESULT',
        self::RT_SAMPLING_START => 'RT_SAMPLING_START',
        self::RT_SAMPLING_STOP => 'RT_SAMPLING_STOP',
        self::MARK_ORIENTATION => 'MARK_ORIENTATION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(MsgType::class, \Mpp\Msg_MsgType::class);

