<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp\SysEvent;

use UnexpectedValueException;

/**
 * Protobuf type <code>mpp.SysEvent.EventType</code>
 */
class EventType
{
    /**
     * Generated from protobuf enum <code>STARTUP = 0;</code>
     */
    const STARTUP = 0;
    /**
     * Generated from protobuf enum <code>REBOOT = 1;</code>
     */
    const REBOOT = 1;
    /**
     * Generated from protobuf enum <code>SHUTDOWN = 2;</code>
     */
    const SHUTDOWN = 2;
    /**
     * Generated from protobuf enum <code>SLEEP = 3;</code>
     */
    const SLEEP = 3;

    private static $valueToName = [
        self::STARTUP => 'STARTUP',
        self::REBOOT => 'REBOOT',
        self::SHUTDOWN => 'SHUTDOWN',
        self::SLEEP => 'SLEEP',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

