<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp\SamplingStart;

use UnexpectedValueException;

/**
 * sampling modes
 *
 * Protobuf type <code>mpp.SamplingStart.SamplingMode</code>
 */
class SamplingMode
{
    /**
     * periodic
     *
     * Generated from protobuf enum <code>PERIODIC = 0;</code>
     */
    const PERIODIC = 0;
    /**
     * triggered
     *
     * Generated from protobuf enum <code>TRIGGERED = 1;</code>
     */
    const TRIGGERED = 1;
    /**
     * adaptive
     *
     * Generated from protobuf enum <code>ADAPTIVE = 2;</code>
     */
    const ADAPTIVE = 2;

    private static $valueToName = [
        self::PERIODIC => 'PERIODIC',
        self::TRIGGERED => 'TRIGGERED',
        self::ADAPTIVE => 'ADAPTIVE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

