<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp\LogEntry;

use UnexpectedValueException;

/**
 * entry types
 *
 * Protobuf type <code>mpp.LogEntry.EntryType</code>
 */
class EntryType
{
    /**
     * system is unusable
     *
     * Generated from protobuf enum <code>EMERGENCY = 0;</code>
     */
    const EMERGENCY = 0;
    /**
     * immediate action required
     *
     * Generated from protobuf enum <code>ALERT = 1;</code>
     */
    const ALERT = 1;
    /**
     * critical condition
     *
     * Generated from protobuf enum <code>CRITICAL = 2;</code>
     */
    const CRITICAL = 2;
    /**
     * error
     *
     * Generated from protobuf enum <code>ERROR = 3;</code>
     */
    const ERROR = 3;
    /**
     * warning
     *
     * Generated from protobuf enum <code>WARNING = 4;</code>
     */
    const WARNING = 4;
    /**
     * significant message during regular operation
     *
     * Generated from protobuf enum <code>NOTICE = 5;</code>
     */
    const NOTICE = 5;
    /**
     * informative message
     *
     * Generated from protobuf enum <code>INFO = 6;</code>
     */
    const INFO = 6;
    /**
     * debug message
     *
     * Generated from protobuf enum <code>DEBUG = 7;</code>
     */
    const DEBUG = 7;

    private static $valueToName = [
        self::EMERGENCY => 'EMERGENCY',
        self::ALERT => 'ALERT',
        self::CRITICAL => 'CRITICAL',
        self::ERROR => 'ERROR',
        self::WARNING => 'WARNING',
        self::NOTICE => 'NOTICE',
        self::INFO => 'INFO',
        self::DEBUG => 'DEBUG',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

