<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp\UpdateStart;

use UnexpectedValueException;

/**
 * update modes
 *
 * Protobuf type <code>mpp.UpdateStart.ModeType</code>
 */
class ModeType
{
    /**
     * device waits for update fragments to be sent in from outside
     *
     * Generated from protobuf enum <code>PUSH = 0;</code>
     */
    const PUSH = 0;
    /**
     * device downloads the update by itself
     *
     * Generated from protobuf enum <code>PULL = 1;</code>
     */
    const PULL = 1;

    private static $valueToName = [
        self::PUSH => 'PUSH',
        self::PULL => 'PULL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

