<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *	Purpose:	Notifies about the end of a communications session. Issued by all MPP nodes before closing a channel.
 *	Reply:		N/D
 *
 * Generated from protobuf message <code>mpp.CommSessionEnd</code>
 */
class CommSessionEnd extends \Google\Protobuf\Internal\Message
{
    /**
     * reason
     *
     * Generated from protobuf field <code>.mpp.CommSessionEnd.ReasonType reason = 1;</code>
     */
    protected $reason = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $reason
     *           reason
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * reason
     *
     * Generated from protobuf field <code>.mpp.CommSessionEnd.ReasonType reason = 1;</code>
     * @return int
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * reason
     *
     * Generated from protobuf field <code>.mpp.CommSessionEnd.ReasonType reason = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkEnum($var, \Mpp\CommSessionEnd\ReasonType::class);
        $this->reason = $var;

        return $this;
    }

}

