<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *	Purpose:	Notifies about the start of a communications session. Issued by each MPP source node after opening a 
 *				channel to a sink node.
 *	Reply:		N/D
 *
 * Generated from protobuf message <code>mpp.CommSessionBegin</code>
 */
class CommSessionBegin extends \Google\Protobuf\Internal\Message
{
    /**
     * node ID (device serial number or similar unique identifier)
     *
     * Generated from protobuf field <code>uint64 node_id = 1;</code>
     */
    protected $node_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $node_id
     *           node ID (device serial number or similar unique identifier)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * node ID (device serial number or similar unique identifier)
     *
     * Generated from protobuf field <code>uint64 node_id = 1;</code>
     * @return int|string
     */
    public function getNodeId()
    {
        return $this->node_id;
    }

    /**
     * node ID (device serial number or similar unique identifier)
     *
     * Generated from protobuf field <code>uint64 node_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNodeId($var)
    {
        GPBUtil::checkUint64($var);
        $this->node_id = $var;

        return $this;
    }

}

