<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

if (false) {
    /**
     * This class is deprecated. Use Mpp\ConfigRead\Layer instead.
     * @deprecated
     */
    class ConfigRead_Layer {}
}
class_exists(ConfigRead\Layer::class);
@trigger_error('Mpp\ConfigRead_Layer is deprecated and will be removed in the next major release. Use Mpp\ConfigRead\Layer instead', E_USER_DEPRECATED);

