<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

if (false) {
    /**
     * This class is deprecated. Use Mpp\ConfigWrite\Layer instead.
     * @deprecated
     */
    class ConfigWrite_Layer {}
}
class_exists(ConfigWrite\Layer::class);
@trigger_error('Mpp\ConfigWrite_Layer is deprecated and will be removed in the next major release. Use Mpp\ConfigWrite\Layer instead', E_USER_DEPRECATED);

