<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

if (false) {
    /**
     * This class is deprecated. Use Mpp\ConfigReadResult\Block instead.
     * @deprecated
     */
    class ConfigReadResult_Block {}
}
class_exists(ConfigReadResult\Block::class);
@trigger_error('Mpp\ConfigReadResult_Block is deprecated and will be removed in the next major release. Use Mpp\ConfigReadResult\Block instead', E_USER_DEPRECATED);

