<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *	Purpose:	Contains the configuration changes to be written to a device. The changes are volatile at first, unless
 *				followed by ConfigWrite command that commits them permanently, or ConfigRevert that reverts them 
 *				back to the previous saved state. Usually sent from a server or configuration utility.
 *	Reply:		ConfigResult				
 *
 * Generated from protobuf message <code>mpp.ConfigWrite</code>
 */
class ConfigWrite extends \Google\Protobuf\Internal\Message
{
    /**
     * user configuration (changes only)
     *
     * Generated from protobuf field <code>.mpp.ConfigWrite.Layer user_config = 1;</code>
     */
    protected $user_config = null;
    /**
     * IDs of symbols to be locked	
     *
     * Generated from protobuf field <code>repeated uint32 lock_symbol_ids = 2;</code>
     */
    private $lock_symbol_ids;
    /**
     * IDs of symbols to be unlocked
     *
     * Generated from protobuf field <code>repeated uint32 unlock_symbol_ids = 3;</code>
     */
    private $unlock_symbol_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Mpp\ConfigWrite\Layer $user_config
     *           user configuration (changes only)
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $lock_symbol_ids
     *           IDs of symbols to be locked	
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $unlock_symbol_ids
     *           IDs of symbols to be unlocked
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * user configuration (changes only)
     *
     * Generated from protobuf field <code>.mpp.ConfigWrite.Layer user_config = 1;</code>
     * @return \Mpp\ConfigWrite\Layer|null
     */
    public function getUserConfig()
    {
        return $this->user_config;
    }

    public function hasUserConfig()
    {
        return isset($this->user_config);
    }

    public function clearUserConfig()
    {
        unset($this->user_config);
    }

    /**
     * user configuration (changes only)
     *
     * Generated from protobuf field <code>.mpp.ConfigWrite.Layer user_config = 1;</code>
     * @param \Mpp\ConfigWrite\Layer $var
     * @return $this
     */
    public function setUserConfig($var)
    {
        GPBUtil::checkMessage($var, \Mpp\ConfigWrite\Layer::class);
        $this->user_config = $var;

        return $this;
    }

    /**
     * IDs of symbols to be locked	
     *
     * Generated from protobuf field <code>repeated uint32 lock_symbol_ids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLockSymbolIds()
    {
        return $this->lock_symbol_ids;
    }

    /**
     * IDs of symbols to be locked	
     *
     * Generated from protobuf field <code>repeated uint32 lock_symbol_ids = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLockSymbolIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->lock_symbol_ids = $arr;

        return $this;
    }

    /**
     * IDs of symbols to be unlocked
     *
     * Generated from protobuf field <code>repeated uint32 unlock_symbol_ids = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnlockSymbolIds()
    {
        return $this->unlock_symbol_ids;
    }

    /**
     * IDs of symbols to be unlocked
     *
     * Generated from protobuf field <code>repeated uint32 unlock_symbol_ids = 3;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnlockSymbolIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->unlock_symbol_ids = $arr;

        return $this;
    }

}

