<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>mpp.InstallOrient</code>
 */
class InstallOrient extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated float sensor_orient = 1;</code>
     */
    private $sensor_orient;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $sensor_orient
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated float sensor_orient = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSensorOrient()
    {
        return $this->sensor_orient;
    }

    /**
     * Generated from protobuf field <code>repeated float sensor_orient = 1;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSensorOrient($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->sensor_orient = $arr;

        return $this;
    }

}

