<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TODO
 *
 * Generated from protobuf message <code>mpp.LogEntry</code>
 */
class LogEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * entry type
     *
     * Generated from protobuf field <code>.mpp.LogEntry.EntryType entry_type = 1;</code>
     */
    protected $entry_type = 0;
    /**
     * system timestamp (ms)
     *
     * Generated from protobuf field <code>uint64 sys_timestamp = 2;</code>
     */
    protected $sys_timestamp = 0;
    /**
     * UTC timestamp (Unix epoch, ms)
     *
     * Generated from protobuf field <code>uint64 utc_timestamp = 3;</code>
     */
    protected $utc_timestamp = 0;
    /**
     * origin of the entry
     *
     * Generated from protobuf field <code>string origin = 4;</code>
     */
    protected $origin = '';
    /**
     * text
     *
     * Generated from protobuf field <code>string text = 5;</code>
     */
    protected $text = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $entry_type
     *           entry type
     *     @type int|string $sys_timestamp
     *           system timestamp (ms)
     *     @type int|string $utc_timestamp
     *           UTC timestamp (Unix epoch, ms)
     *     @type string $origin
     *           origin of the entry
     *     @type string $text
     *           text
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * entry type
     *
     * Generated from protobuf field <code>.mpp.LogEntry.EntryType entry_type = 1;</code>
     * @return int
     */
    public function getEntryType()
    {
        return $this->entry_type;
    }

    /**
     * entry type
     *
     * Generated from protobuf field <code>.mpp.LogEntry.EntryType entry_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setEntryType($var)
    {
        GPBUtil::checkEnum($var, \Mpp\LogEntry\EntryType::class);
        $this->entry_type = $var;

        return $this;
    }

    /**
     * system timestamp (ms)
     *
     * Generated from protobuf field <code>uint64 sys_timestamp = 2;</code>
     * @return int|string
     */
    public function getSysTimestamp()
    {
        return $this->sys_timestamp;
    }

    /**
     * system timestamp (ms)
     *
     * Generated from protobuf field <code>uint64 sys_timestamp = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSysTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->sys_timestamp = $var;

        return $this;
    }

    /**
     * UTC timestamp (Unix epoch, ms)
     *
     * Generated from protobuf field <code>uint64 utc_timestamp = 3;</code>
     * @return int|string
     */
    public function getUtcTimestamp()
    {
        return $this->utc_timestamp;
    }

    /**
     * UTC timestamp (Unix epoch, ms)
     *
     * Generated from protobuf field <code>uint64 utc_timestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUtcTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->utc_timestamp = $var;

        return $this;
    }

    /**
     * origin of the entry
     *
     * Generated from protobuf field <code>string origin = 4;</code>
     * @return string
     */
    public function getOrigin()
    {
        return $this->origin;
    }

    /**
     * origin of the entry
     *
     * Generated from protobuf field <code>string origin = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOrigin($var)
    {
        GPBUtil::checkString($var, True);
        $this->origin = $var;

        return $this;
    }

    /**
     * text
     *
     * Generated from protobuf field <code>string text = 5;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * text
     *
     * Generated from protobuf field <code>string text = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

}

