<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

if (false) {
    /**
     * This class is deprecated. Use Mpp\LogEntry\EntryType instead.
     * @deprecated
     */
    class LogEntry_EntryType {}
}
class_exists(LogEntry\EntryType::class);
@trigger_error('Mpp\LogEntry_EntryType is deprecated and will be removed in the next major release. Use Mpp\LogEntry\EntryType instead', E_USER_DEPRECATED);

