<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *	Purpose:	Starts reading the device system log for the given time period. 
 *	Reply:		N/D
 *
 * Generated from protobuf message <code>mpp.LogReadStart</code>
 */
class LogReadStart extends \Google\Protobuf\Internal\Message
{
    /**
     * period from (UTC, Unix epoch, ms)
     *
     * Generated from protobuf field <code>uint64 utc_period_from = 1;</code>
     */
    protected $utc_period_from = 0;
    /**
     * period to (UTC, Unix epoch, ms)
     *
     * Generated from protobuf field <code>uint64 utc_period_to = 2;</code>
     */
    protected $utc_period_to = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $utc_period_from
     *           period from (UTC, Unix epoch, ms)
     *     @type int|string $utc_period_to
     *           period to (UTC, Unix epoch, ms)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * period from (UTC, Unix epoch, ms)
     *
     * Generated from protobuf field <code>uint64 utc_period_from = 1;</code>
     * @return int|string
     */
    public function getUtcPeriodFrom()
    {
        return $this->utc_period_from;
    }

    /**
     * period from (UTC, Unix epoch, ms)
     *
     * Generated from protobuf field <code>uint64 utc_period_from = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUtcPeriodFrom($var)
    {
        GPBUtil::checkUint64($var);
        $this->utc_period_from = $var;

        return $this;
    }

    /**
     * period to (UTC, Unix epoch, ms)
     *
     * Generated from protobuf field <code>uint64 utc_period_to = 2;</code>
     * @return int|string
     */
    public function getUtcPeriodTo()
    {
        return $this->utc_period_to;
    }

    /**
     * period to (UTC, Unix epoch, ms)
     *
     * Generated from protobuf field <code>uint64 utc_period_to = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUtcPeriodTo($var)
    {
        GPBUtil::checkUint64($var);
        $this->utc_period_to = $var;

        return $this;
    }

}

