<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *
 * Generated from protobuf message <code>mpp.MarkOrientation</code>
 */
class MarkOrientation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float front_heading = 1;</code>
     */
    protected $front_heading = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $front_heading
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float front_heading = 1;</code>
     * @return float
     */
    public function getFrontHeading()
    {
        return $this->front_heading;
    }

    /**
     * Generated from protobuf field <code>float front_heading = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setFrontHeading($var)
    {
        GPBUtil::checkFloat($var);
        $this->front_heading = $var;

        return $this;
    }

}

