<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

if (false) {
    /**
     * This class is deprecated. Use Mpp\Msg\MsgType instead.
     * @deprecated
     */
    class Msg_MsgType {}
}
class_exists(Msg\MsgType::class);
@trigger_error('Mpp\Msg_MsgType is deprecated and will be removed in the next major release. Use Mpp\Msg\MsgType instead', E_USER_DEPRECATED);

