<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

if (false) {
    /**
     * This class is deprecated. Use Mpp\Msg\PayloadType instead.
     * @deprecated
     */
    class Msg_PayloadType {}
}
class_exists(Msg\PayloadType::class);
@trigger_error('Mpp\Msg_PayloadType is deprecated and will be removed in the next major release. Use Mpp\Msg\PayloadType instead', E_USER_DEPRECATED);

