<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>mpp.PingingStart</code>
 */
class PingingStart extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 period = 1;</code>
     */
    protected $period = 0;
    /**
     * Generated from protobuf field <code>uint64 duration = 2;</code>
     */
    protected $duration = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $period
     *     @type int|string $duration
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 period = 1;</code>
     * @return int|string
     */
    public function getPeriod()
    {
        return $this->period;
    }

    /**
     * Generated from protobuf field <code>uint64 period = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPeriod($var)
    {
        GPBUtil::checkUint64($var);
        $this->period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 duration = 2;</code>
     * @return int|string
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Generated from protobuf field <code>uint64 duration = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkUint64($var);
        $this->duration = $var;

        return $this;
    }

}

