<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

if (false) {
    /**
     * This class is deprecated. Use Mpp\Samples\Sample instead.
     * @deprecated
     */
    class Samples_Sample {}
}
class_exists(Samples\Sample::class);
@trigger_error('Mpp\Samples_Sample is deprecated and will be removed in the next major release. Use Mpp\Samples\Sample instead', E_USER_DEPRECATED);

