<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * data sample message
 *
 * Generated from protobuf message <code>mpp.Samples</code>
 */
class Samples extends \Google\Protobuf\Internal\Message
{
    /**
     * blocks of samples
     *
     * Generated from protobuf field <code>repeated .mpp.Samples.Block blocks = 2;</code>
     */
    private $blocks;
    protected $tag;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $tag_hash
     *           sample tag hash
     *     @type string $tag_str
     *           sample tag string
     *     @type \Mpp\Samples\Block[]|\Google\Protobuf\Internal\RepeatedField $blocks
     *           blocks of samples
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * sample tag hash
     *
     * Generated from protobuf field <code>uint32 tag_hash = 1;</code>
     * @return int
     */
    public function getTagHash()
    {
        return $this->readOneof(1);
    }

    public function hasTagHash()
    {
        return $this->hasOneof(1);
    }

    /**
     * sample tag hash
     *
     * Generated from protobuf field <code>uint32 tag_hash = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTagHash($var)
    {
        GPBUtil::checkUint32($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * sample tag string
     *
     * Generated from protobuf field <code>string tag_str = 3;</code>
     * @return string
     */
    public function getTagStr()
    {
        return $this->readOneof(3);
    }

    public function hasTagStr()
    {
        return $this->hasOneof(3);
    }

    /**
     * sample tag string
     *
     * Generated from protobuf field <code>string tag_str = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTagStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * blocks of samples
     *
     * Generated from protobuf field <code>repeated .mpp.Samples.Block blocks = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBlocks()
    {
        return $this->blocks;
    }

    /**
     * blocks of samples
     *
     * Generated from protobuf field <code>repeated .mpp.Samples.Block blocks = 2;</code>
     * @param \Mpp\Samples\Block[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBlocks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Mpp\Samples\Block::class);
        $this->blocks = $arr;

        return $this;
    }

    /**
     * @return string
     */
    public function getTag()
    {
        return $this->whichOneof("tag");
    }

}

