<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *
 * Generated from protobuf message <code>mpp.SamplingStart</code>
 */
class SamplingStart extends \Google\Protobuf\Internal\Message
{
    /**
     * sample set tag string
     *
     * Generated from protobuf field <code>string tag_str = 1;</code>
     */
    protected $tag_str = '';
    /**
     * symbol IDs
     *
     * Generated from protobuf field <code>repeated uint32 symbol_ids = 2;</code>
     */
    private $symbol_ids;
    /**
     * Generated from protobuf field <code>uint64 sampling_period = 3;</code>
     */
    protected $sampling_period = 0;
    /**
     * Generated from protobuf field <code>bool allow_partial_samples = 4;</code>
     */
    protected $allow_partial_samples = false;
    /**
     * Generated from protobuf field <code>uint32 num_buffered_samples = 5;</code>
     */
    protected $num_buffered_samples = 0;
    /**
     * Generated from protobuf field <code>uint32 num_transmitted_samples = 6;</code>
     */
    protected $num_transmitted_samples = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tag_str
     *           sample set tag string
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $symbol_ids
     *           symbol IDs
     *     @type int|string $sampling_period
     *     @type bool $allow_partial_samples
     *     @type int $num_buffered_samples
     *     @type int $num_transmitted_samples
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * sample set tag string
     *
     * Generated from protobuf field <code>string tag_str = 1;</code>
     * @return string
     */
    public function getTagStr()
    {
        return $this->tag_str;
    }

    /**
     * sample set tag string
     *
     * Generated from protobuf field <code>string tag_str = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTagStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag_str = $var;

        return $this;
    }

    /**
     * symbol IDs
     *
     * Generated from protobuf field <code>repeated uint32 symbol_ids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSymbolIds()
    {
        return $this->symbol_ids;
    }

    /**
     * symbol IDs
     *
     * Generated from protobuf field <code>repeated uint32 symbol_ids = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSymbolIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->symbol_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 sampling_period = 3;</code>
     * @return int|string
     */
    public function getSamplingPeriod()
    {
        return $this->sampling_period;
    }

    /**
     * Generated from protobuf field <code>uint64 sampling_period = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSamplingPeriod($var)
    {
        GPBUtil::checkUint64($var);
        $this->sampling_period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool allow_partial_samples = 4;</code>
     * @return bool
     */
    public function getAllowPartialSamples()
    {
        return $this->allow_partial_samples;
    }

    /**
     * Generated from protobuf field <code>bool allow_partial_samples = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllowPartialSamples($var)
    {
        GPBUtil::checkBool($var);
        $this->allow_partial_samples = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 num_buffered_samples = 5;</code>
     * @return int
     */
    public function getNumBufferedSamples()
    {
        return $this->num_buffered_samples;
    }

    /**
     * Generated from protobuf field <code>uint32 num_buffered_samples = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setNumBufferedSamples($var)
    {
        GPBUtil::checkUint32($var);
        $this->num_buffered_samples = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 num_transmitted_samples = 6;</code>
     * @return int
     */
    public function getNumTransmittedSamples()
    {
        return $this->num_transmitted_samples;
    }

    /**
     * Generated from protobuf field <code>uint32 num_transmitted_samples = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setNumTransmittedSamples($var)
    {
        GPBUtil::checkUint32($var);
        $this->num_transmitted_samples = $var;

        return $this;
    }

}

