<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *
 * Generated from protobuf message <code>mpp.SamplingStop</code>
 */
class SamplingStop extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tag_str = 1;</code>
     */
    protected $tag_str = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tag_str
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tag_str = 1;</code>
     * @return string
     */
    public function getTagStr()
    {
        return $this->tag_str;
    }

    /**
     * Generated from protobuf field <code>string tag_str = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTagStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag_str = $var;

        return $this;
    }

}

