<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

if (false) {
    /**
     * This class is deprecated. Use Mpp\Samples\Block instead.
     * @deprecated
     */
    class Samples_Block {}
}
class_exists(Samples\Block::class);
@trigger_error('Mpp\Samples_Block is deprecated and will be removed in the next major release. Use Mpp\Samples\Block instead', E_USER_DEPRECATED);

