<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

if (false) {
    /**
     * This class is deprecated. Use Mpp\SessionEnd\Reason instead.
     * @deprecated
     */
    class SessionEnd_Reason {}
}
class_exists(SessionEnd\Reason::class);
@trigger_error('Mpp\SessionEnd_Reason is deprecated and will be removed in the next major release. Use Mpp\SessionEnd\Reason instead', E_USER_DEPRECATED);

