<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * session start message: issued by MPP source nodes after opening a comms channel
 *
 * Generated from protobuf message <code>mpp.SessionBegin</code>
 */
class SessionBegin extends \Google\Protobuf\Internal\Message
{
    /**
     * node ID; identifies the device
     *
     * Generated from protobuf field <code>uint64 node_id = 1;</code>
     */
    protected $node_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $node_id
     *           node ID; identifies the device
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * node ID; identifies the device
     *
     * Generated from protobuf field <code>uint64 node_id = 1;</code>
     * @return int|string
     */
    public function getNodeId()
    {
        return $this->node_id;
    }

    /**
     * node ID; identifies the device
     *
     * Generated from protobuf field <code>uint64 node_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNodeId($var)
    {
        GPBUtil::checkUint64($var);
        $this->node_id = $var;

        return $this;
    }

}

