<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *	Purpose:	Executes a system control command.
 *	Reply:		N/D
 *
 * Generated from protobuf message <code>mpp.SysControl</code>
 */
class SysControl extends \Google\Protobuf\Internal\Message
{
    /**
     * command
     *
     * Generated from protobuf field <code>.mpp.SysControl.CommandType command_type = 1;</code>
     */
    protected $command_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $command_type
     *           command
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * command
     *
     * Generated from protobuf field <code>.mpp.SysControl.CommandType command_type = 1;</code>
     * @return int
     */
    public function getCommandType()
    {
        return $this->command_type;
    }

    /**
     * command
     *
     * Generated from protobuf field <code>.mpp.SysControl.CommandType command_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCommandType($var)
    {
        GPBUtil::checkEnum($var, \Mpp\SysControl\CommandType::class);
        $this->command_type = $var;

        return $this;
    }

}

