<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *	Purpose:	Transfers the result of a tachograph command which returns an APDU.
 *	Reply:		N/D
 *
 * Generated from protobuf message <code>mpp.TachoAPDUResult</code>
 */
class TachoAPDUResult extends \Google\Protobuf\Internal\Message
{
    /**
     * session ID
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     */
    protected $session_id = 0;
    /**
     * command result
     *
     * Generated from protobuf field <code>.mpp.TachoResultType result = 2;</code>
     */
    protected $result = 0;
    /**
     * APDU or ATR
     *
     * Generated from protobuf field <code>optional bytes apdu = 3;</code>
     */
    protected $apdu = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $session_id
     *           session ID
     *     @type int $result
     *           command result
     *     @type string $apdu
     *           APDU or ATR
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * session ID
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     * @return int
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * session ID
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkUint32($var);
        $this->session_id = $var;

        return $this;
    }

    /**
     * command result
     *
     * Generated from protobuf field <code>.mpp.TachoResultType result = 2;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * command result
     *
     * Generated from protobuf field <code>.mpp.TachoResultType result = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Mpp\TachoResultType::class);
        $this->result = $var;

        return $this;
    }

    /**
     * APDU or ATR
     *
     * Generated from protobuf field <code>optional bytes apdu = 3;</code>
     * @return string
     */
    public function getApdu()
    {
        return isset($this->apdu) ? $this->apdu : '';
    }

    public function hasApdu()
    {
        return isset($this->apdu);
    }

    public function clearApdu()
    {
        unset($this->apdu);
    }

    /**
     * APDU or ATR
     *
     * Generated from protobuf field <code>optional bytes apdu = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setApdu($var)
    {
        GPBUtil::checkString($var, False);
        $this->apdu = $var;

        return $this;
    }

}

