<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *	Purpose:	Turns on status LEDs to help indentify particular cards. If no card numbers are provided, all LEDs
 *				are turned off.
 *	Reply:		TachoResult
 *
 * Generated from protobuf message <code>mpp.TachoCardShowBlinkenlights</code>
 */
class TachoCardShowBlinkenlights extends \Google\Protobuf\Internal\Message
{
    /**
     * card serial numbers with LEDs on
     *
     * Generated from protobuf field <code>repeated uint64 on_card_serials = 1;</code>
     */
    private $on_card_serials;
    /**
     * card serial numbers with LEDs off
     *
     * Generated from protobuf field <code>repeated uint64 off_card_serials = 2;</code>
     */
    private $off_card_serials;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $on_card_serials
     *           card serial numbers with LEDs on
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $off_card_serials
     *           card serial numbers with LEDs off
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * card serial numbers with LEDs on
     *
     * Generated from protobuf field <code>repeated uint64 on_card_serials = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOnCardSerials()
    {
        return $this->on_card_serials;
    }

    /**
     * card serial numbers with LEDs on
     *
     * Generated from protobuf field <code>repeated uint64 on_card_serials = 1;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOnCardSerials($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->on_card_serials = $arr;

        return $this;
    }

    /**
     * card serial numbers with LEDs off
     *
     * Generated from protobuf field <code>repeated uint64 off_card_serials = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOffCardSerials()
    {
        return $this->off_card_serials;
    }

    /**
     * card serial numbers with LEDs off
     *
     * Generated from protobuf field <code>repeated uint64 off_card_serials = 2;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOffCardSerials($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->off_card_serials = $arr;

        return $this;
    }

}

