<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *	Purpose:	Transfers a list of tachograph company cards and their statuses.
 *	Reply:		N/D
 *
 * Generated from protobuf message <code>mpp.TachoCardInfo</code>
 */
class TachoCardInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * list of company cards
     *
     * Generated from protobuf field <code>repeated .mpp.TachoCardInfo.Card cards = 1;</code>
     */
    private $cards;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Mpp\TachoCardInfo\Card>|\Google\Protobuf\Internal\RepeatedField $cards
     *           list of company cards
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * list of company cards
     *
     * Generated from protobuf field <code>repeated .mpp.TachoCardInfo.Card cards = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCards()
    {
        return $this->cards;
    }

    /**
     * list of company cards
     *
     * Generated from protobuf field <code>repeated .mpp.TachoCardInfo.Card cards = 1;</code>
     * @param array<\Mpp\TachoCardInfo\Card>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCards($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Mpp\TachoCardInfo\Card::class);
        $this->cards = $arr;

        return $this;
    }

}

