<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *	Purpose:	Starts remote data download from VU. If company card card ATR is provided, the existing authentication 
 *				(if any) is overridden and new one will be initiated.
 *	Reply:		TachoResult
 *
 * Generated from protobuf message <code>mpp.TachoDownloadStart</code>
 */
class TachoDownloadStart extends \Google\Protobuf\Internal\Message
{
    /**
     * download session ID (unique, generated by caller)
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     */
    protected $session_id = 0;
    /**
     * company card ATR
     *
     * Generated from protobuf field <code>bytes card_atr = 2;</code>
     */
    protected $card_atr = '';
    /**
     * list of requests
     *
     * Generated from protobuf field <code>bytes request_list = 3;</code>
     */
    protected $request_list = '';
    /**
     * session timeout, ms
     *
     * Generated from protobuf field <code>uint64 session_timeout = 4;</code>
     */
    protected $session_timeout = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $session_id
     *           download session ID (unique, generated by caller)
     *     @type string $card_atr
     *           company card ATR
     *     @type string $request_list
     *           list of requests
     *     @type int|string $session_timeout
     *           session timeout, ms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * download session ID (unique, generated by caller)
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     * @return int
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * download session ID (unique, generated by caller)
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkUint32($var);
        $this->session_id = $var;

        return $this;
    }

    /**
     * company card ATR
     *
     * Generated from protobuf field <code>bytes card_atr = 2;</code>
     * @return string
     */
    public function getCardAtr()
    {
        return $this->card_atr;
    }

    /**
     * company card ATR
     *
     * Generated from protobuf field <code>bytes card_atr = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCardAtr($var)
    {
        GPBUtil::checkString($var, False);
        $this->card_atr = $var;

        return $this;
    }

    /**
     * list of requests
     *
     * Generated from protobuf field <code>bytes request_list = 3;</code>
     * @return string
     */
    public function getRequestList()
    {
        return $this->request_list;
    }

    /**
     * list of requests
     *
     * Generated from protobuf field <code>bytes request_list = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestList($var)
    {
        GPBUtil::checkString($var, False);
        $this->request_list = $var;

        return $this;
    }

    /**
     * session timeout, ms
     *
     * Generated from protobuf field <code>uint64 session_timeout = 4;</code>
     * @return int|string
     */
    public function getSessionTimeout()
    {
        return $this->session_timeout;
    }

    /**
     * session timeout, ms
     *
     * Generated from protobuf field <code>uint64 session_timeout = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSessionTimeout($var)
    {
        GPBUtil::checkUint64($var);
        $this->session_timeout = $var;

        return $this;
    }

}

