<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *	Purpose:	Cancels the remote data download session identified by the given target: a particular session ID, or 
 *				any session involving the given card. If no target is supplied, all active sessions are cancelled. 
 *	Reply:		TachoResult
 *
 * Generated from protobuf message <code>mpp.TachoCardSessionCancel</code>
 */
class TachoCardSessionCancel extends \Google\Protobuf\Internal\Message
{
    protected $target;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $session_id
     *           session ID
     *     @type int|string $card_serial
     *           card serial number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * session ID
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     * @return int
     */
    public function getSessionId()
    {
        return $this->readOneof(1);
    }

    public function hasSessionId()
    {
        return $this->hasOneof(1);
    }

    /**
     * session ID
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkUint32($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * card serial number
     *
     * Generated from protobuf field <code>uint64 card_serial = 2;</code>
     * @return int|string
     */
    public function getCardSerial()
    {
        return $this->readOneof(2);
    }

    public function hasCardSerial()
    {
        return $this->hasOneof(2);
    }

    /**
     * card serial number
     *
     * Generated from protobuf field <code>uint64 card_serial = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCardSerial($var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getTarget()
    {
        return $this->whichOneof("target");
    }

}

