<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *	Purpose:	Transfers a data file manifest when the file is either downloaded fully or an error occurs.
 *	Reply:		N/D
 *
 * Generated from protobuf message <code>mpp.TachoFileManifest</code>
 */
class TachoFileManifest extends \Google\Protobuf\Internal\Message
{
    /**
     * download session ID
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     */
    protected $session_id = 0;
    /**
     * request number [0..n]
     *
     * Generated from protobuf field <code>uint32 request_num = 2;</code>
     */
    protected $request_num = 0;
    /**
     * request type
     *
     * Generated from protobuf field <code>uint32 request_type = 3;</code>
     */
    protected $request_type = 0;
    /**
     * request date (UTC, Unix epoch, ms)
     *
     * Generated from protobuf field <code>optional uint64 requested_date = 4;</code>
     */
    protected $requested_date = null;
    /**
     * total file size, B
     *
     * Generated from protobuf field <code>uint32 size = 5;</code>
     */
    protected $size = 0;
    /**
     * file checksum
     *
     * Generated from protobuf field <code>uint32 checksum = 6;</code>
     */
    protected $checksum = 0;
    /**
     * file download result
     *
     * Generated from protobuf field <code>.mpp.TachoResultType result = 7;</code>
     */
    protected $result = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $session_id
     *           download session ID
     *     @type int $request_num
     *           request number [0..n]
     *     @type int $request_type
     *           request type
     *     @type int|string $requested_date
     *           request date (UTC, Unix epoch, ms)
     *     @type int $size
     *           total file size, B
     *     @type int $checksum
     *           file checksum
     *     @type int $result
     *           file download result
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * download session ID
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     * @return int
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * download session ID
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkUint32($var);
        $this->session_id = $var;

        return $this;
    }

    /**
     * request number [0..n]
     *
     * Generated from protobuf field <code>uint32 request_num = 2;</code>
     * @return int
     */
    public function getRequestNum()
    {
        return $this->request_num;
    }

    /**
     * request number [0..n]
     *
     * Generated from protobuf field <code>uint32 request_num = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRequestNum($var)
    {
        GPBUtil::checkUint32($var);
        $this->request_num = $var;

        return $this;
    }

    /**
     * request type
     *
     * Generated from protobuf field <code>uint32 request_type = 3;</code>
     * @return int
     */
    public function getRequestType()
    {
        return $this->request_type;
    }

    /**
     * request type
     *
     * Generated from protobuf field <code>uint32 request_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRequestType($var)
    {
        GPBUtil::checkUint32($var);
        $this->request_type = $var;

        return $this;
    }

    /**
     * request date (UTC, Unix epoch, ms)
     *
     * Generated from protobuf field <code>optional uint64 requested_date = 4;</code>
     * @return int|string
     */
    public function getRequestedDate()
    {
        return isset($this->requested_date) ? $this->requested_date : 0;
    }

    public function hasRequestedDate()
    {
        return isset($this->requested_date);
    }

    public function clearRequestedDate()
    {
        unset($this->requested_date);
    }

    /**
     * request date (UTC, Unix epoch, ms)
     *
     * Generated from protobuf field <code>optional uint64 requested_date = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRequestedDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->requested_date = $var;

        return $this;
    }

    /**
     * total file size, B
     *
     * Generated from protobuf field <code>uint32 size = 5;</code>
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * total file size, B
     *
     * Generated from protobuf field <code>uint32 size = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->size = $var;

        return $this;
    }

    /**
     * file checksum
     *
     * Generated from protobuf field <code>uint32 checksum = 6;</code>
     * @return int
     */
    public function getChecksum()
    {
        return $this->checksum;
    }

    /**
     * file checksum
     *
     * Generated from protobuf field <code>uint32 checksum = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setChecksum($var)
    {
        GPBUtil::checkUint32($var);
        $this->checksum = $var;

        return $this;
    }

    /**
     * file download result
     *
     * Generated from protobuf field <code>.mpp.TachoResultType result = 7;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * file download result
     *
     * Generated from protobuf field <code>.mpp.TachoResultType result = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Mpp\TachoResultType::class);
        $this->result = $var;

        return $this;
    }

}

