<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *	Purpose:	Requests information about all or a subset of tachograph company cards.
 *	Reply:		TachoCardInfo
 *
 * Generated from protobuf message <code>mpp.TachoCardInfoRequest</code>
 */
class TachoCardInfoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * smartcard serial numbers (optional)
     *
     * Generated from protobuf field <code>repeated uint64 card_serials = 1;</code>
     */
    private $card_serials;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $card_serials
     *           smartcard serial numbers (optional)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * smartcard serial numbers (optional)
     *
     * Generated from protobuf field <code>repeated uint64 card_serials = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCardSerials()
    {
        return $this->card_serials;
    }

    /**
     * smartcard serial numbers (optional)
     *
     * Generated from protobuf field <code>repeated uint64 card_serials = 1;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCardSerials($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->card_serials = $arr;

        return $this;
    }

}

