<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *	Purpose:	Cancels the remote data download session with the given session ID. If session ID is not provided, any 
 *				running download session is cancelled.
 *	Reply:		TachoResult
 *
 * Generated from protobuf message <code>mpp.TachoDownloadCancel</code>
 */
class TachoDownloadCancel extends \Google\Protobuf\Internal\Message
{
    /**
     * download session ID (cancels any session if not set)
     *
     * Generated from protobuf field <code>optional uint32 session_id = 1;</code>
     */
    protected $session_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $session_id
     *           download session ID (cancels any session if not set)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * download session ID (cancels any session if not set)
     *
     * Generated from protobuf field <code>optional uint32 session_id = 1;</code>
     * @return int
     */
    public function getSessionId()
    {
        return isset($this->session_id) ? $this->session_id : 0;
    }

    public function hasSessionId()
    {
        return isset($this->session_id);
    }

    public function clearSessionId()
    {
        unset($this->session_id);
    }

    /**
     * download session ID (cancels any session if not set)
     *
     * Generated from protobuf field <code>optional uint32 session_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkUint32($var);
        $this->session_id = $var;

        return $this;
    }

}

