<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *	Purpose:	Starts a new tachograph authentication session with a company card.
 *	Reply:		TachoAPDUResult
 *
 * Generated from protobuf message <code>mpp.TachoCardSessionStart</code>
 */
class TachoCardSessionStart extends \Google\Protobuf\Internal\Message
{
    /**
     * session ID (unique, generated by caller)
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     */
    protected $session_id = 0;
    /**
     * card serial number
     *
     * Generated from protobuf field <code>uint64 card_serial = 2;</code>
     */
    protected $card_serial = 0;
    /**
     * session timeout, ms
     *
     * Generated from protobuf field <code>uint64 session_timeout = 3;</code>
     */
    protected $session_timeout = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $session_id
     *           session ID (unique, generated by caller)
     *     @type int|string $card_serial
     *           card serial number
     *     @type int|string $session_timeout
     *           session timeout, ms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * session ID (unique, generated by caller)
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     * @return int
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * session ID (unique, generated by caller)
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkUint32($var);
        $this->session_id = $var;

        return $this;
    }

    /**
     * card serial number
     *
     * Generated from protobuf field <code>uint64 card_serial = 2;</code>
     * @return int|string
     */
    public function getCardSerial()
    {
        return $this->card_serial;
    }

    /**
     * card serial number
     *
     * Generated from protobuf field <code>uint64 card_serial = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCardSerial($var)
    {
        GPBUtil::checkUint64($var);
        $this->card_serial = $var;

        return $this;
    }

    /**
     * session timeout, ms
     *
     * Generated from protobuf field <code>uint64 session_timeout = 3;</code>
     * @return int|string
     */
    public function getSessionTimeout()
    {
        return $this->session_timeout;
    }

    /**
     * session timeout, ms
     *
     * Generated from protobuf field <code>uint64 session_timeout = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSessionTimeout($var)
    {
        GPBUtil::checkUint64($var);
        $this->session_timeout = $var;

        return $this;
    }

}

