<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpp/mpp.proto

namespace Mpp;

if (false) {
    /**
     * This class is deprecated. Use Mpp\UpdateStart\Mode instead.
     * @deprecated
     */
    class UpdateStart_Mode {}
}
class_exists(UpdateStart\Mode::class);
@trigger_error('Mpp\UpdateStart_Mode is deprecated and will be removed in the next major release. Use Mpp\UpdateStart\Mode instead', E_USER_DEPRECATED);

