<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *	Purpose:	Starts device firmware update. 
 *	Reply:		UpdateResult
 *
 * Generated from protobuf message <code>mpp.UpdateStart</code>
 */
class UpdateStart extends \Google\Protobuf\Internal\Message
{
    /**
     * update session ID (unique, generated by caller)
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     */
    protected $session_id = 0;
    /**
     * update mode
     *
     * Generated from protobuf field <code>.mpp.UpdateStart.ModeType update_mode = 2;</code>
     */
    protected $update_mode = 0;
    /**
     * source URL (pull mode only)
     *
     * Generated from protobuf field <code>optional string source_url = 3;</code>
     */
    protected $source_url = null;
    /**
     * size of update binary, bytes
     *
     * Generated from protobuf field <code>uint32 source_size = 4;</code>
     */
    protected $source_size = 0;
    /**
     * checksum of update binary, CRC32
     *
     * Generated from protobuf field <code>uint32 source_crc = 5;</code>
     */
    protected $source_crc = 0;
    /**
     * session timeout, ms
     *
     * Generated from protobuf field <code>uint64 session_timeout = 6;</code>
     */
    protected $session_timeout = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $session_id
     *           update session ID (unique, generated by caller)
     *     @type int $update_mode
     *           update mode
     *     @type string $source_url
     *           source URL (pull mode only)
     *     @type int $source_size
     *           size of update binary, bytes
     *     @type int $source_crc
     *           checksum of update binary, CRC32
     *     @type int|string $session_timeout
     *           session timeout, ms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * update session ID (unique, generated by caller)
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     * @return int
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * update session ID (unique, generated by caller)
     *
     * Generated from protobuf field <code>uint32 session_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkUint32($var);
        $this->session_id = $var;

        return $this;
    }

    /**
     * update mode
     *
     * Generated from protobuf field <code>.mpp.UpdateStart.ModeType update_mode = 2;</code>
     * @return int
     */
    public function getUpdateMode()
    {
        return $this->update_mode;
    }

    /**
     * update mode
     *
     * Generated from protobuf field <code>.mpp.UpdateStart.ModeType update_mode = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUpdateMode($var)
    {
        GPBUtil::checkEnum($var, \Mpp\UpdateStart\ModeType::class);
        $this->update_mode = $var;

        return $this;
    }

    /**
     * source URL (pull mode only)
     *
     * Generated from protobuf field <code>optional string source_url = 3;</code>
     * @return string
     */
    public function getSourceUrl()
    {
        return isset($this->source_url) ? $this->source_url : '';
    }

    public function hasSourceUrl()
    {
        return isset($this->source_url);
    }

    public function clearSourceUrl()
    {
        unset($this->source_url);
    }

    /**
     * source URL (pull mode only)
     *
     * Generated from protobuf field <code>optional string source_url = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_url = $var;

        return $this;
    }

    /**
     * size of update binary, bytes
     *
     * Generated from protobuf field <code>uint32 source_size = 4;</code>
     * @return int
     */
    public function getSourceSize()
    {
        return $this->source_size;
    }

    /**
     * size of update binary, bytes
     *
     * Generated from protobuf field <code>uint32 source_size = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSourceSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->source_size = $var;

        return $this;
    }

    /**
     * checksum of update binary, CRC32
     *
     * Generated from protobuf field <code>uint32 source_crc = 5;</code>
     * @return int
     */
    public function getSourceCrc()
    {
        return $this->source_crc;
    }

    /**
     * checksum of update binary, CRC32
     *
     * Generated from protobuf field <code>uint32 source_crc = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSourceCrc($var)
    {
        GPBUtil::checkUint32($var);
        $this->source_crc = $var;

        return $this;
    }

    /**
     * session timeout, ms
     *
     * Generated from protobuf field <code>uint64 session_timeout = 6;</code>
     * @return int|string
     */
    public function getSessionTimeout()
    {
        return $this->session_timeout;
    }

    /**
     * session timeout, ms
     *
     * Generated from protobuf field <code>uint64 session_timeout = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSessionTimeout($var)
    {
        GPBUtil::checkUint64($var);
        $this->session_timeout = $var;

        return $this;
    }

}

